import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")

PORT = int(os.getenv("PORT", 8080))

WELCOME_MESSAGE = 'hi'
TELEGRAM_ADMIN_CHAT_ID = os.getenv("ADMIN_CHAT_ID")
TELEGRAM_CHANNEL_ID = '-1001534769195'
REPLY_TO_THIS_MESSAGE = 'hui'
WRONG_REPLY = 'aaaa'